#!/bin/zsh
##
# aiwenár - zsh configuration for xterm's
#

bindkey '\e[2~'   overwrite-mode
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# enable 256 colors

export TERM=xterm-256color

