#!/bin/zsh
##
# aiwenár - battery monitor
# 

(( ! $#BATN )) && BATN=1
(( ! $#ADPN )) && ADPN="ADP0"
(( ! $#BAT_L1 )) && BAT_L1=60
(( ! $#BAT_L2 )) && BAT_L2=25

if [ "$TERM" = "linux" ] ; then
  function batt_info ()
  {
    local co
    zstyle -a ':batt_info:adapter' 'color' co
    if [ `cat "/sys/class/power_supply/$ADPN/online"` = 1 ] ; then
      batt_info_msg="%{$co%}☇%{$resetc%} "
      return
    fi
    local st=$[`cat "/sys/class/power_supply/BAT$BATN/charge_now"`*100/`cat "/sys/class/power_supply/BAT$BATN/charge_full"`]
    if [ $st > $BAT_L1 ] ; then
      zstyle -a ':batt_info:batt' 'level1' co
    elif [ $st > $BAT_L2 ] ; then
      zstyle -a ':batt_info:batt' 'level2' co
    else
      zstyle -a ':batt_info:batt' 'level3' co
    fi
    batt_info_msg="%{$co%}$st%{$resetc%} "
  }
else
  function batt_info ()
  {
    batt_info_msg=""
  }
fi
