#!/bin/zsh
##
# aiwenár - battery monitor

function check_battery () {
  batts=""
}

if [ "$TERM" = "linux" ] ; then
  BAT="BAT1"
  if [ -e "/sys/class/power_supply/$BAT" ] ; then
    function check_battery () {
      local c=""
      local s=$[`cat /sys/class/power_supply/$BAT/charge_now`*100/`cat /sys/class/power_supply/$BAT/charge_full`]
      if [[ $s -gt 76 ]] ; then
        c=$green
      elif [[ $s -gt 30 ]] ; then
        c=$yellow
      else
        c=$red
      fi
      batts="%{$c%}%{$s%}%{$resetc%} "
    }
  fi
fi
